### ISSUE TITLE
Question - send cmd command on windows?

### ISSUE THREAD

**Issue by joerithienpont** [jeroenwienk/homey-desktop-device#1]
Hey Jeroen,

Project looks cool, but I'm unsure if it's finished? Can I send a cmd command to my desktop from homey somehow?

**Comment by jeroenwienk** [comment]
> Hey Jeroen,
> 
> Project looks cool, but I'm unsure if it's finished? Can I send a cmd command to my desktop from homey somehow?

Yes there is a Flow card to run a command and create an output. This ouput can then be given an id and used in another Flow to print it to the timeline or something.
